# Generated by Django 5.1.3 on 2024-11-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=8)),
                ('scheduled', models.CharField(choices=[('a', 'Agendado'), ('d', 'Disponível')], default='d', max_length=1)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=8)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=8)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=8)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=8)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gerenciador_horario.client')),
            ],
        ),
    ]
