# Generated by Django 5.1.3 on 2024-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
