# Generated by Django 5.1.3 on 2024-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0003_monday_scheduled_thursday_scheduled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monday',
            name='id',
        ),
        migrations.AlterField(
            model_name='monday',
            name='client_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='monday',
            name='client_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monday',
            name='horario',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
