# Generated by Django 5.1.3 on 2024-11-22 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0004_remove_monday_id_alter_monday_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='client_number',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(99999999999)]),
        ),
    ]
