# Generated by Django 5.1.3 on 2024-11-22 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0007_alter_monday_client_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='client_number',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
