# Generated by Django 5.1.3 on 2025-05-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0011_remove_friday_id_remove_thursday_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia', to='gerenciador_horario.diadisponivel')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gerenciador_horario.client')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_horario.diadisponivel')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_horario.horariodisponivel')),
            ],
            options={
                'unique_together': {('dia', 'horario')},
            },
        ),
    ]
