# Generated by Django 5.1.3 on 2025-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0012_diadisponivel_horariodisponivel_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponivel',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
