# Generated by Django 5.1.3 on 2025-05-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0012_diadisponivel_horariodisponivel_agendamento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('dia', 'horario')},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gerenciador_horario.client'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='telefone',
        ),
    ]
