# Generated by Django 5.1.3 on 2025-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0013_horariodisponivel_agendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.CharField(max_length=20),
        ),
    ]
