# Generated by Django 5.1.3 on 2025-05-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0013_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='nome_cliente',
            new_name='cliente',
        ),
    ]
