# Generated by Django 5.1.3 on 2025-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0014_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.IntegerField(default=11111111111),
        ),
    ]
