# Generated by Django 5.1.3 on 2025-06-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0015_agendamento_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_disponivel', to='gerenciador_horario.diadisponivel'),
        ),
    ]
