# Generated by Django 5.1.3 on 2025-08-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_horario', '0016_alter_agendamento_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponivel',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gerenciador_horario.diadisponivel'),
        ),
    ]
